drop table if exists three_layer_schedule_task;

CREATE TABLE `three_layer_schedule_task` (
  `id` bigint NOT NULL,
  `biz_type` varchar(48) DEFAULT NULL,
  `biz_context` nvarchar(4086) DEFAULT NULL,
  `biz_id` varchar(48) DEFAULT NULL,
  `create_at` datetime(6) DEFAULT NULL,
  `update_at` datetime(6) DEFAULT NULL,
  `retry_times` int DEFAULT 0,
  `max_retry_times` int DEFAULT 0,
  `retry_duration_in_second` int DEFAULT 0,
  `need_retry` bit DEFAULT 0,
  `status` varchar(20) NOT NULL,
  `cancel_reason` varchar(255) DEFAULT NULL,
  `sub_task_count` int DEFAULT 0,
  `parent_id` bigint DEFAULT NULL,
  `task_type` varchar(20) DEFAULT NULL,
  `topic` varchar(128) DEFAULT NULL,
  `tag` varchar(128) DEFAULT NULL,
  `exec_result` nvarchar(4086) DEFAULT NULL,
  PRIMARY KEY (`id`),
  index (`parent_id`),
  index (`status`),
  index (`task_type`),
  index (`topic`),
  index (`tag`),
  index (`biz_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `three_layer_schedule_task_history` (
  `id` bigint NOT NULL,
  `biz_type` varchar(48) DEFAULT NULL,
  `biz_context` nvarchar(4086) DEFAULT NULL,
  `biz_id` varchar(48) DEFAULT NULL,
  `create_at` datetime(6) DEFAULT NULL,
  `update_at` datetime(6) DEFAULT NULL,
  `retry_times` int DEFAULT 0,
  `max_retry_times` int DEFAULT 0,
  `retry_duration_in_second` int DEFAULT 0,
  `need_retry` bit DEFAULT 0,
  `status` varchar(20) NOT NULL,
  `cancel_reason` varchar(255) DEFAULT NULL,
  `sub_task_count` int DEFAULT 0,
  `parent_id` bigint DEFAULT NULL,
  `task_type` varchar(20) DEFAULT NULL,
  `topic` varchar(128) DEFAULT NULL,
  `tag` varchar(128) DEFAULT NULL,
  `exec_result` nvarchar(4086) DEFAULT NULL,
  PRIMARY KEY (`id`),
  index (`parent_id`),
  index (`status`),
  index (`task_type`),
  index (`topic`),
  index (`tag`),
  index (`biz_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;